import {Inter} from 'next/font/google'
import {AuthProvider} from "@/context/AuthContext";
import "@/utils/debug";
import ResponsiveAppBar from "@/components/NavBar";
import React from "react";
import {Providers} from "@/app/providers";
import {Connect} from "@/components/Connect";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <AuthProvider>
            <body className={inter.className}>
            <Providers>
                <header>
                    <ResponsiveAppBar/>
                </header>

                <main>
                    <Connect/>
                    {children}
                </main>

                <footer>
                    {/* footer content here */}
                </footer>
            </Providers>
            </body>
        </AuthProvider>
        </html>
    )
}
